version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: hotel-api-postgres
    environment:
      POSTGRES_DB: hotel_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d hotel_db"]
      interval: 10s
      timeout: 5s
      retries: 10

  hotel-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hotel-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SERVER_PORT: 8092
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hotel_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8092:8092"

volumes:
  postgres_data:
