spring.application.name=hotel-api
server.port=8092
spring.profiles.active=h2

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

springdoc.swagger-ui.path=/swagger-ui.html
